spring.datasource.url=jdbc:postgresql://localhost/isaacmc_series
spring.datasource.username=postgres
spring.datasource.password=Kbblade0901@
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

spring.jpa.hibernate.ddl-auto=update